#!/usr/bin/env bash

set -uo pipefail

#AWS_EC2_ID="$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)"
#_PROCESS="ossec-hids-agent"
#SLACK_WEBHOOK="https://hooks.slack.com/services/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"
BITDEFENDER_URL="https://cloud.gravityzone.bitdefender.com/Packages/NIX/0/XQEupy/Bitdefender_for_Linux.tar"

## Functions:
# It notifies Slack and exists with error if the previous process ended badly.
#notify_slack_if_error() {
#  curl -X POST \
#    --data-urlencode "payload={\"channel\": \"#infra-alerts\", \"username\": \"AWS EC2 $AWS_EC2_ID\", \"text\": \"$1\", \"icon_emoji\": \":ossec:\"}" \
#  $SLACK_WEBHOOK &> /dev/null
#  exit 1
#}

echo "Start Bitdefender BEST Installation"

# Install wget
sudo yum install wget -y
# Get Linux tar
cd /tmp && sudo wget $BITDEFENDER_URL
#
sudo tar -xvf Bitdefender_for_Linux.tar
#
sudo chmod +x installer
#
./installer
# Clean up tmp
cd /tmp && sudo rm -rf Bitdefender_for_Linux.tar

echo "Bitdefender is up and running!"
