#!/bin/bash

set -euo pipefail

#AWS_EC2_ID="$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)"
#JUMPCLOUD_AGENT="jcagent"
#JUMPCLOUD_DIR="/opt/jc"
JUMPCLOUD_KEY="91a691b81dc7ea281f722f77f5a72ef8e563d78d"
#SLACK_WEBHOOK="https://hooks.slack.com/services/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"

### Functions:
## It notifies Slack and exists with error if the previous process ended badly.
#notify_slack_if_error() {
#  curl -X POST \
#    --data-urlencode "payload={\"channel\": \"#infra-alerts\", \"username\": \"AWS EC2 $AWS_EC2_ID\", \"text\": \"$1\", \"icon_emoji\": \":jumpcloud:\"}" \
#  $SLACK_WEBHOOK &> /dev/null
#  exit 1
#}

# It installs JumpCloud by using the installer provided by the service.
curl \
  --tlsv1.2 \
  --silent \
  --show-error \
  --header 'x-connect-key: '$JUMPCLOUD_KEY'' \
  https://kickstart.jumpcloud.com/Kickstart | sudo bash


#start_jumpcloud() {
#  service $JUMPCLOUD_AGENT start
#}
#
#test_if_installed() {
#  yum list installed jcagent &> /dev/null
#}
#
#test_if_started() {
#  service $JUMPCLOUD_AGENT status &> /dev/null
#}
#
## Check if the process jcagent is installed:
#if ! test_if_installed; then
#  echo "Installing the $JUMPCLOUD_AGENT process."
#  if ! install_jumpcloud; then
#    notify_slack_if_error "Unable to install JumpCloud ($JUMPCLOUD_AGENT) on the instance *$(hostname)*."
#  fi
#fi
#
## Check if the process jcagent is started
#if ! test_if_started; then
#  echo "Starting the $JUMPCLOUD_AGENT process."
#  if ! start_jumpcloud; then
#    notify_slack_if_error "Unable to start JumpCloud ($JUMPCLOUD_AGENT) on the instance *$(hostname)*."
#  fi
#fi
#
#echo "JumpCloud ($JUMPCLOUD_AGENT) is up and running!"
