#!/usr/bin/env bash

set -uo pipefail

#AWS_EC2_ID="$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)"
OSSEC_PROCESS="ossec-hids-agent"
#SLACK_WEBHOOK="https://hooks.slack.com/services/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"
#
## Functions:
# It notifies Slack and exists with error if the previous process ended badly.
#notify_slack_if_error() {
#  curl -X POST \
#    --data-urlencode "payload={\"channel\": \"#infra-alerts\", \"username\": \"AWS EC2 $AWS_EC2_ID\", \"text\": \"$1\", \"icon_emoji\": \":ossec:\"}" \
#  $SLACK_WEBHOOK &> /dev/null
#  exit 1
#}

# Add Yum repo configuration
wget -q -O - https://updates.atomicorp.com/installers/atomic | sudo bash -yes
# Agent
sudo yum install ossec-hids-agent -y
# Adding password for agent-auth
echo "4216361d6876cb2c51fbc1892a720fcb" > /var/ossec/etc/authd.pass
# 
/var/ossec/bin/agent-auth -A "$(hostname)-$AWS_EC2_ID" -m 10.0.3.217
sed -i 's/10.66.6.211/10.0.3.217/g' /var/ossec/etc/ossec.conf
/var/ossec/bin/ossec-control start

#start_nessus() {
#  service $OSSEC_PROCESS start 1> /dev/null
#}
#
#test_if_installed() {
#  yum list installed $OSSEC_PROCESS &> /dev/null
#}
#
#test_if_started() {
#  service $OSSEC_PROCESS status &> /dev/null
#}
#
## Check if the process jcagent is installed:
#if ! test_if_installed; then
#  echo "Installing the $OSSEC_PROCESS process."
#  if ! install_nessus; then
#    notify_slack_if_error "Unable to install Ossec on the instance *$(hostname)*."
#  fi
#fi
#
## Check if the process jcagent is starteds
#if ! test_if_started; then
#  echo "Starting the $OSSEC_PROCESS process."
#  if ! start_nessus; then
#    notify_slack_if_error "Unable to start Ossec on the instance *$(hostname)*."
#  fi
#fi

echo "Ossec ($OSSEC_PROCESS) is up and running!"
